vim.opt.wrap = true -- Enable line wrap
vim.opt.cursorline = false -- Highlight the current line
vim.opt.inccommand = "split" -- Preview substitutions live, as you type!
vim.opt.autoindent = true
vim.opt.autoread = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.numberwidth = 4
vim.opt.cursorcolumn = false
vim.wo.spell = true
vim.opt.colorcolumn = "0"
