vim.o.wrap = false -- Enable line wrap
vim.o.cursorline = false -- Highlight the current line
vim.o.inccommand = "split" -- Preview substitutions live, as you type!
vim.o.autoindent = true
vim.o.autoread = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.o.numberwidth = 4
vim.o.cursorcolumn = false
vim.o.spell = true
vim.o.colorcolumn = "0"
vim.o.textwidth = 80
