"$schema" = 'https://starship.rs/config-schema.json'

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#f6acf4'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "fg:color_fg0"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = "󰣇 "
EndeavourOS = " "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Pop = " "

[username]
show_always = true
style_user = "fg:color_fg0"
style_root = "fg:color_fg0"

[directory]
style = "fg:color_fg0"

truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"
# Show only the current directory name
truncate_to_repo = true


[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = " "


[git_status]
disabled = false
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
staged = "+"
conflicted = "×"
deleted = "✘"
modified = "!"
renamed = "»"
stashed = "$"


[nodejs]
symbol = " "



[c]
symbol = " "



[rust]
symbol = " "



[golang]
symbol = " "



[php]
symbol = " "



[java]
symbol = " "



[kotlin]
symbol = " "



[haskell]
symbol = " "



[python]
symbol = " "



[docker_context]
symbol = " "



[conda]
symbol = " "



[aws]
symbol = " "

[buf]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "


[guix_shell]
symbol = " "


[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "


[package]
symbol = "󰏗 "

[pijul_channel]
symbol = "🪺 "


[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "


[scala]
symbol = " "

[spack]
symbol = "🅢 "
[time]
disabled = false
time_format = "%H:%M:%S"



[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
