name: ShellCheck Linting

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
