name: ShellCheck Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: koalaman/shellcheck-action@v1
        with:
          # Prüft alle Shell-Skripte (*.sh) im Repository
          shellcheck: '**/*.sh'
