name: ShellCheck Linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: koalaman/shellcheck-action@v1
        with:
          # Check all shell scripts (*.sh) in the repository
          shellcheck: '**/*.sh'
